version: '3.8'

services:
  postgres:
    image: ankane/pgvector
    container_name: askme_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./app/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 10s
      timeout: 5s
      retries: 3

  app:
    build: .
    container_name: askme_app
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - API_TOKEN=${API_TOKEN}
    volumes:
      - .:/app
    env_file:
      - .env
    # Command to run the initialization scripts
    command: >
      sh -c "python app/scripts/load_faq_data.py && python app/scripts/initialize_embeddings.py && uvicorn app.main:app --host 0.0.0.0 --port 8000"

volumes:
  pg_data:
